/*
	Student ID: 1155156680
	Name: Wong Shing Lok
*/

/* Query 1 */
Spool result1.lst
SELECT L.LID, L.LEAGUE_NAME, R.REGION_NAME, L.YEAR
FROM REGIONS R, LEAGUES L
WHERE R.RID = L.RID AND L.SEASON IN ('Spring', 'Summer')
ORDER BY L.LID ASC;
Spool off

/* Query 2 */
Spool result2.lst
SELECT T.TID, T.TEAM_NAME, T.AVERAGE_AGE
FROM TEAMS T, LEAGUES L
WHERE L.CHAMPION_TID = T.TID AND L.SEASON = 'Autumn' AND L.YEAR >= 2015
GROUP BY T.TID, T.TEAM_NAME, T.AVERAGE_AGE
HAVING COUNT(*)>1
ORDER BY T.TID ASC;
Spool off

/* Query 3 */
CREATE OR REPLACE VIEW TEMP AS
SELECT T.TID, T.TEAM_NAME, T.AVERAGE_AGE, L.SEASON, COUNT(L.LID) AS W_NUM
FROM TEAMS T, LEAGUES L
WHERE CHAMPION_TID = TID
GROUP BY T.TID, T.TEAM_NAME, T.AVERAGE_AGE, L.SEASON;
Spool result3.lst
SELECT *
FROM TEMP T1
WHERE W_NUM = (SELECT MAX(T2.W_NUM) 
FROM TEMP T2 
WHERE T1.SEASON=T2.SEASON
)
ORDER BY T1.TID ASC, T1.SEASON ASC; 
Spool off
DROP VIEW TEMP;

/* Query 4 */
Spool result4.lst
SELECT * FROM (
SELECT S.SID, S.SPONSOR_NAME, COUNT(SUP.LID) AS L_NUM
FROM SPONSORS S, SUPPORT SUP, LEAGUES L
WHERE S.SID = SUP.SID AND L.LID = SUP.LID
GROUP BY S.SID, S.SPONSOR_NAME
ORDER BY S.SID ASC
)
WHERE ROWNUM <=5; 
Spool off

/* Query 5 */
Spool result5.lst
SELECT DISTINCT L.LID, L.LEAGUE_NAME
FROM LEAGUES L, SUPPORT SUP
WHERE L.SEASON IN ('Autumn', 'Winter') AND L.LID = SUP.LID
AND SUP.SID IN (SELECT SID FROM SPONSORS WHERE MARKET_VALUE > 50)
AND L.CHAMPION_TID IN (SELECT TID FROM TEAMS WHERE AVERAGE_AGE < 30)
ORDER BY L.LID DESC;
Spool off

/* Query 6 */
CREATE OR REPLACE VIEW TEMP AS 
SELECT S.SID, R.RID, MARKET_VALUE, FOOTBALL_RANKING, (SUM(SPONSORSHIP)/(SQRT(MARKET_VALUE)*LOG(2,SQRT(FOOTBALL_RANKING)+1))) AS HOT
FROM REGIONS R, LEAGUES L, SUPPORT SUP, SPONSORS S
WHERE R.RID = L.RID AND S.SID = SUP.SID AND SUP.LID = L.LID
GROUP BY S.SID, R.RID, MARKET_VALUE, FOOTBALL_RANKING;
Spool result6.lst
SELECT SID, HOT
FROM TEMP
WHERE HOT = (SELECT MAX(HOT) FROM TEMP WHERE MARKET_VALUE > 40 AND FOOTBALL_RANKING < 10)
ORDER BY SID DESC;
Spool off

/* Query 7 */
Spool result7.lst
SELECT RID, HOT_4, HOT_5, HOT_6, HOT_7, GREATEST(NVL(HOT_4,0),NVL(HOT_5,0),NVL(HOT_6,0),NVL(HOT_7,0)) AS HOT_HIGH
FROM (
SELECT R.RID,
(SELECT HOT FROM TEMP T4 WHERE T4.SID=4 AND T4.RID = R.RID) AS HOT_4,
(SELECT HOT FROM TEMP T5 WHERE T5.SID=5 AND T5.RID = R.RID) AS HOT_5,
(SELECT HOT FROM TEMP T6 WHERE T6.SID=6 AND T6.RID = R.RID) AS HOT_6,
(SELECT HOT FROM TEMP T7 WHERE T7.SID=7 AND T7.RID = R.RID) AS HOT_7
FROM REGIONS R
)
ORDER BY RID DESC;
Spool off
DROP VIEW TEMP;

/* Query 8 */
CREATE OR REPLACE VIEW TEMP AS 
SELECT CHAMPION_TID, COUNT(CHAMPION_TID) AS WON_GAMES
FROM LEAGUES
GROUP BY CHAMPION_TID;
Spool result8.lst
SELECT DISTINCT S.SID, S.SPONSOR_NAME
FROM SPONSORS S, LEAGUES L, SUPPORT SUP
WHERE S.SID=SUP.SID AND SUP.LID = L.LID
AND L.CHAMPION_TID IN (SELECT CHAMPION_TID FROM TEMP WHERE WON_GAMES = (SELECT MAX(WON_GAMES) FROM TEMP))
ORDER BY S.SID;
Spool off
DROP VIEW TEMP;
